version: "3"

services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    ports:
      - "25565:25565/tcp"
    env_file:
      ./minecraft.env
    volumes:
      - ./data:/data